apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efood
      service: starter
  template:
    metadata:
      labels:
        app: efood
        service: starter
        sidecar.istio.io/inject: "true"
        version: "1"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: starter
        image: ghcr.io/wofood/efood_starter
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - name: starter
            protocol: TCP
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: efood-config
