apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalties-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efood
      service: loyalties
  template:
    metadata:
      labels:
        app: efood
        service: loyalties
        sidecar.istio.io/inject: "true"
        version: "1"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: loyalties
        image: ghcr.io/wofood/efood_loyalties
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - name: loyalties
            protocol: TCP
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: efood-config
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
