apiVersion: v1
kind: Service
metadata:
  name: loyalties-svc
  labels:
    app: efood
    service: loyalties
spec:
  selector:
    app: efood
    service: loyalties
  ports:
    - name: http-port
      port: 3000
